nameOverride: "kafka-sink"

kafkasink:
 - name: reviews-sink
   topic: globex.reviews
   partitions: 1
   contentMode: binary
  
kafka:
  bootstrapServer:
  secret: kafka-secret

argocd:
  enabled: true
  syncwave: "-1"