---
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: {{ include "knative-kafkasource.name" . }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    {{- include "knative-kafkasource.argocd-syncwave" . | nindent 4 }}
spec:
  bootstrapServers:
    - {{ .Values.kafka.bootstrapServer }}
  topics:
    {{- toYaml .Values.topics | nindent 4 }}
  net:    
    {{- if eq .Values.kafka.securityProtocol "SASL_SSL" }}
    tls:
      enable: true
      caCert: {}
      cert: {}
      key: {}
    {{- end }}    
    sasl:
      enable: true
      user:
        secretKeyRef:
          name: {{ .Values.kafka.secret }}
          key: user
      password:
        secretKeyRef:
          name: {{ .Values.kafka.secret }}
          key: password
      type:
        secretKeyRef:
          name: {{ .Values.kafka.secret }}
          key: sasl.mechanism
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: {{ .Values.broker }}
