apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: {{ include "knative-broker.name" . }}
  annotations:
    eventing.knative.dev/broker.class: MTChannelBasedBroker
    {{- include "knative-broker.argocd-syncwave" . | nindent 4 }}